### ISSUE TITLE
关于例题11.1 OJ提交时,由于数组下标为负造成报段错误的问题

### ISSUE THREAD

**Issue by daimcgit** [BenedictYoung/Practice#3]
因为'A'~'Z' 减去 '-'后是负值, 作为数组下标会在OJ中判定为段错误.
修复内容如下
75 76行
child[str[2] - 'A'] = str[0] - 'A';
child[str[1] - 'A'] = str[0] - 'A';
调整为
if (str[2] != '-')
{
    child[str[2] - 'A'] = str[0] - 'A';
}
if (str[1] != '-')
{
    child[str[1] - 'A'] = str[0] - 'A';
}
[11.1 fix bug 20220314.txt](https://github.com/BenedictYoung/Practice/files/8243148/11.1.fix.bug.20220314.txt)

**Comment by zebangyang** [comment]
感谢你的提问，代码已经修改完成，最新代码可参考https://github.com/BenedictYoung/Practice/blob/master/Chapter11/11.1.cpp
